RepasoPruebaP1/Models/Equipo.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RepasoPruebaP1.Models
{
    public class Equipo
    {
        [Key] //El ID es nuestro KEY
        public int Id { get; set; }
        [Required]
        [MaxLength(100)]
        [DisplayName("Ingrese el nombre: ")]
        public string Nombre { get; set; }
        [Range(0, 100)]
        public int PartidosJugados { get; set; }
        [Range(0, 100)]
        public int PartidosGanados { get; set; }
        [Range(0, 100)]
        public int PartidosEmpatados { get; set; }
        [Range(0, 100)]
        public int PartidosPerdidos { get; set; }
        [Range(0, 200)]
        public int TotalPartidos
            //El set se utiliza cuando quieres asignar un valor, y el get se utiliza cuando quieres obtener un valor.
        {
            get
            {
                // Calculando el total de partidos como la suma de ganados, perdidos y empatados
                return PartidosGanados + PartidosPerdidos + PartidosEmpatados;
            }
        }

        // Propiedad calculada para TotalPuntos
        public int TotalPuntos
        {
            get
            {
                return (PartidosGanados * 3) + (PartidosEmpatados);  // 3 puntos por victoria y 1 por empate
            }
        }


    }
}

RepasoPruebaP1/Models/ErrorViewModel.cs
namespace RepasoPruebaP1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RepasoPruebaP1/Controllers/EquipoController.cs
using Microsoft.AspNetCore.Mvc;
using RepasoPruebaP1.Models;
using RepasoPruebaP1.Views.Repositories;  // Asegúrate de tener el espacio de nombres correcto


namespace RepasoPruebaP1.Controllers
{
    public class EquipoController : Controller
    {
        // Debes de poner el nombre que asignaste en viws Equipo
        public IActionResult List() // Acción para devolver una vista con la lista de equipos
        {
            EquipoRepository repositorio = new EquipoRepository();
            var equipos = repositorio.DevuelveListadoEquipos();
            return View(equipos);
        }

        public IActionResult EditarEquipo()
        {
            Equipo ldu = new Equipo
            {
                Id = 1,
                Nombre = "LDU",
                PartidosGanados = 10,
                PartidosPerdidos = 5,
                PartidosEmpatados = 5
            };
            return View(ldu);
        }
        
    }
}

RepasoPruebaP1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RepasoPruebaP1.Models;

namespace RepasoPruebaP1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RepasoPruebaP1/Views/Equipo/EditarEquipo.cshtml
@model RepasoPruebaP1.Models.Equipo

<h4>Equipo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarEquipo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartidosJugados" class="control-label"></label>
                <input asp-for="PartidosJugados" class="form-control" />
                <span asp-validation-for="PartidosJugados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartidosGanados" class="control-label"></label>
                <input asp-for="PartidosGanados" class="form-control" />
                <span asp-validation-for="PartidosGanados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartidosEmpatados" class="control-label"></label>
                <input asp-for="PartidosEmpatados" class="form-control" />
                <span asp-validation-for="PartidosEmpatados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PartidosPerdidos" class="control-label"></label>
                <input asp-for="PartidosPerdidos" class="form-control" />
                <span asp-validation-for="PartidosPerdidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPartidos" class="control-label"></label>
                <input asp-for="TotalPartidos" class="form-control" />
                <span asp-validation-for="TotalPartidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPuntos" class="control-label"></label>
                <input asp-for="TotalPuntos" class="form-control" />
                <span asp-validation-for="TotalPuntos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RepasoPruebaP1/Views/Equipo/List.cshtml
@model IEnumerable<RepasoPruebaP1.Models.Equipo>

<p>
    <a class="btn-success" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartidosJugados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartidosGanados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartidosEmpatados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartidosPerdidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPartidos)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartidosJugados)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartidosGanados)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartidosEmpatados)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartidosPerdidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPartidos)
            </td>
            <td>
                    @Html.ActionLink("Edit", "EditarEquipo"/*tiene q ser el mismo q el que pusiste en la vista */, new { id=item.Id }, new { @class = "btn btn-success" /*Diseño a los botones*/ }) | 
                    @Html.ActionLink("Details", "Details", new {  }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

RepasoPruebaP1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <br><br>
    <br><br>
    <!--
    <button>Un Boton</button>
    <button class="SegundoBoton">Otro Boton</button>
    <button class="btn-success">Boton de bootstrap</button>
    -->
</div>

RepasoPruebaP1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RepasoPruebaP1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" /> <!--Llame a la hoja de estilos que cree en wwwroot -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RepasoPruebaP1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipo" asp-action="List">Tabla de Posiciones</a> <!--Agregue una pestaña que diga Tabla de Posiciones y 
                                                                                                                                         me muestre la lista (list) del "Equipo" -->
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RepasoPruebaP1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>